theme: jekyll-theme-cayman
title: Java Backend Classroom
description: From Fundamentals to Enterprise & AI

# Custom CSS and JS links
head:
  - "<link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>"
  - "<script src='https://code.jquery.com/jquery-3.5.1.slim.min.js'></script>"
  - "<script src='https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.5/dist/umd/popper.min.js'></script>"
  - "<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>"
